version: '3.7'

services:
  numbers-new-php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www

  numbers-new-php-cli:
    build:
      context: ./php-cli
    volumes:
      - ../src:/var/www
    stdin_open: true
    tty: true

  numbers-new-nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - numbers-new-php-fpm

  numbers-new-database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=db_numbers
      - MYSQL_USER=numbesr
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql